version: '3'

services:
  loki:
    image: docker.io/grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /u01/mydev/containers-fs-layout/grafana-loki/etc/loki-config.yaml:/etc/loki/loki-config.yaml
    restart: unless-stopped
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

